package it.polimi.ingsw.utils.messages.server.action;

import it.polimi.ingsw.client.ClientController;
import it.polimi.ingsw.server.model.boards.Player;

import java.util.List;

/**
 * Server message that notifies the client of the game's end via natural causes or disconnection
 */
public class EndGameMessage implements ServerActionMessage {

    private final List<Player> players;
    private final boolean disconnection;


    /**
     * Constructor for a EndGameMessage given the leaderboard and a disconnections flag
     * @param players List of Player objects that contain the information needed to create the final leaderboard
     * @param disconnection True if the end of the game has been generated by a disconnection
     */
    public EndGameMessage(List<Player> players, boolean disconnection) {
        this.players = players;
        this.disconnection = disconnection;
    }


    @Override
    public void doAction(ClientController client) {
        client.notifyEndGame(players, disconnection);
        client.destroy();
    }
}
